project:
  type: website
  output-dir: ../docs

website:
  sidebar:
    style: docked
    search: true
    contents:
      - text: "Introduction"
        href: index.ipynb
      - section: "Black-Scholes-Merton and Binomial Trees"
        contents:
          - text: "Stock Price Behaviour and Assumptions Under BSM and Binomial Models"
            href: stockOverview.ipynb
          - text: "Test Cases for BSM and Binomial C++ Pricing Library"
            href: testCases.ipynb
          - text: "Implied Volatility, Volatility Smiles and Volatility Surfaces"
            href: volSmile.ipynb
